# Cloudflare Pages 配置文件
# 对于 Next.js 应用，使用 @cloudflare/next-on-pages

name = "dify-nextjs-template"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 构建输出目录配置
pages_build_output_dir = ".vercel/output/static"

# 环境变量配置（也可以在 Cloudflare Dashboard 中设置）
[vars]
NEXT_PUBLIC_DIFY_BASE_URL = "https://dify.allm.link/v1"

[env.production.vars]
# NEXT_PUBLIC_DIFY_API_KEY = "your-api-key"
NEXT_PUBLIC_DIFY_BASE_URL = "https://dify.allm.link/v1"
