# Cloudflare Pages 配置文件
# 对于 Next.js 应用，主要用于设置环境变量和项目配置

name = "dify-nextjs-template"
compatibility_date = "2024-01-01"

# 环境变量配置（可选，也可以在 Cloudflare Dashboard 中设置）
[vars]
# NEXT_PUBLIC_DIFY_BASE_URL = "https://api.dify.ai/v1"

[env.production.vars]
# NEXT_PUBLIC_DIFY_API_KEY = "your-api-key"
NEXT_PUBLIC_DIFY_BASE_URL = "https://dify.allm.link/v1" 